steps:
  - name: "node:20"
    dir: "apps/frontend"
    entrypoint: npm
    args: ["install"]

  - name: "node:20"
    dir: "apps/frontend"
    entrypoint: npm
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "gcr.io/frc-scorigami/frontend:$COMMIT_SHA"
      - "-t"
      - "gcr.io/frc-scorigami/frontend:latest"
      - "apps/frontend"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "--all-tags", "gcr.io/frc-scorigami/frontend"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - scorigami-frontend
      - "--image"
      - "gcr.io/frc-scorigami/frontend:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"

images:
  - "gcr.io/frc-scorigami/frontend"

options:
  logging: GCS_ONLY
  logsBucket: "gs://frc-scorigami-cloudbuild-logs"
